### ISSUE TITLE
Sostituire Amule con QTransmission

### ISSUE THREAD

**Issue by Mte90** [ItalianLinuxSociety/Vademecum#2]
Ad oggi emule e famiglia é utilizzo veramente poco rispetto a torrent.

**Comment by PalinuroSec** [comment]
ho sempre usato transmission che ha anche il forntend web in caso ci si voglia creare una propria torrent box, si mette a votazione uno dei 2 o li inseriamo entrambi?

**Comment by madbob** [comment]
Direi "Transmission", poi le diverse implementazioni KDE, Gnome, web e altro sono tutti clients della stessa cosa.

**Comment by Mte90** [comment]
si non ci ho ripensato, meglio il generico

**Comment by 0iras0r** [comment]
Sostituito con Transmission e nei consigli generici, anche Deluge in quanto multipiattaforma.
