### ISSUE TITLE
LXDE/LXQt

### ISSUE THREAD

**Issue by lugce-it** [ItalianLinuxSociety/Vademecum#35]
Le nuove versioni di Lubuntu sono e saranno basate su LXQt ma la LTS più recente (18.04) dipende ancora da LXDE.

**Comment by lugce-it** [comment]
@madbob desidera includere LXQt nella pagina Ambienti Desktop? Se sì, in aggiunta a o in sostituzione di LXDE?

**Comment by madbob** [comment]
Se LXDE e' stato dismesso direi di mettere solo LXQt. L'alternativa sarebbe metterli entrambi, sapendo che comunque tra un anno LXDE sara' da togliere di nuovo, dunque non vale la pena.
Grazie :-)
