### ISSUE TITLE
Aggiunta di app

### ISSUE THREAD

**Issue by loviuz** [ItalianLinuxSociety/Vademecum#44]
Ho guardato la versione attuale del vademecum: a parte forse 1 o 2 applicazioni non saprei quali aggiungere perché mi sembra bella ricca la lista. Visto che molte persone ormai usano uno smartphone Android piú che un pc, si potrebbe aggiungere un bel po' di applicazioni aperte da F-Droid e descriverle alla stregua delle applicazioni desktop? Mi offro per farlo. Ho usato Scribus un paio di volte, posso provare se va bene come idea.

**Comment by madbob** [comment]
Semmai si rivede la pagina che parla di mobile, si eliminano CyanogenMod e Replicant (non so chi abbia avuto l'idea balorda di aggiungere cose cosi' tanto avanzate in una guida introduttiva per iper-mega-inesperti), si elimina il paragrafo "Per approfondire" nella stessa pagina e si mettono li' due/tre esempi.

Eviterei di aggiungere altre pagine.

**Comment by loviuz** [comment]
Ok. In effetti Replicant l'ho provato tempo fa ma non é da utente medio... Provo a scrivere qui a breve cosa potrei metterci come app per non aumentare le pagine cosí mi dite se possono andare.

**Comment by loviuz** [comment]
Secondo me ci stanno 5 app subito dopo F-Droid, con un po' di descrizione. Propongo:
- AntennaPod: per ascoltare podcast
- OsmAnd+: per navigazione e anche mappatura (se si vuole contribuire)
- k-9 mail: per la gestione email
- DuckDuckGo Browser: browser che riduce i traccianti, attento alla privacy e alternativo al browser predefinito di sistema
- OpenScan: scansiona documenti con la fotocamera e trasformali in pdf.

Non so se browser e client mail siano scontati, però probabilmente sono basilari per cui li terrei. Che ne pensate?

**Comment by loviuz** [comment]
Ho creato la PR qui: https://github.com/ItalianLinuxSociety/Vademecum/pull/45
