### ISSUE TITLE
Aggiornare linux day con il presentation day

### ISSUE THREAD

**Issue by Mte90** [ItalianLinuxSociety/Vademecum#5]

**Comment by madbob** [comment]
Il Vademecum è principalmente pensato per il Linux Day di fine ottobre. Se qualcuno vuole personalizzarselo per altre occasioni ovviamente è benvenuto: pubblichiamo il codice apposta ;-)

**Comment by Mte90** [comment]
Una citazione riguardo la presentation day per dire che vengono fatti due eventi l'anno non ci starebbe male.
Cosiderando lo spazio in quella pagina ce lo possiamo permettere, tanto questi vademecum vengono regalati anche durante il presentation day
