### ISSUE TITLE
Grafica Vademecum

### ISSUE THREAD

**Issue by 68E14F839** [ItalianLinuxSociety/Vademecum#6]
Quando mi ero iscritto a github avevo provato a buttare giù un'idea per la grafica del vademecum. Adesso purtroppo sono troppo impegnato con il lavoro per potervi seguire come vorrei. Vi invio comunque quello che sono riuscito a fare magari potete riutilizzarlo in qualche modo.

Gio

[vademecum_new.zip](https://github.com/ItalianLinuxSociety/Vademecum/files/211698/vademecum_new.zip)

**Comment by 0iras0r** [comment]
Grazie lo stesso, ma non so se è il caso di fare un cambiamento così importante. Direi che per adesso l'urgenza sta nella rivisitazione dei contenuti.
