### ISSUE TITLE
Aggiungere dei siti di community italiane

### ISSUE THREAD

**Issue by Mte90** [ItalianLinuxSociety/Vademecum#7]
Potremmo aggiungere un elenco di siti di community italiane ad esempio:
- Ubuntu italia
- Mozilla Italia
- Wordpress italia

ecc
In questo modo chi é interessato può trovare direttamente i riferimenti che gli possono interessare.

**Comment by 0iras0r** [comment]
È sicuramente un'idea valida, ma il network deve nascere dalla collaborazione. O magari sponsorizzazione, come avviene già per altri enti.
